name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name : Checkout repository
      uses: actions/checkout@v3
      with:
        ref: dev
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/platform/package-lock.json

    - name: Install dependencies
      run: |
        npm install
        npm install -g gh-pages --save-dev
      working-directory: client/platform/

    # - name: Run the tests
    #   run: npm test
    #   working-directory: client/platform/

    - name: Build
      run : npm run build 
      working-directory: client/platform/

    - name: Deploy
      working-directory: client/platform/
      run: |
        git config --global user.name alicia
        git config --global user.email lyciiasci@gmail.com
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy 
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
